# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd872b73e0e3af41eba2b26c091b9889da8b1bab3f79f06582b2c17545c4fb5a282093fe0ced1956be085a13bbaea4affbaf58e5bb072479d34c7c8849182b5b

test:
  secret_key_base: f5c1f91e4842e0374fa50b040b1ed2d0f84780c0033d7c95a21c637d6719be7f9ec4a9240385bffe649a90e2ae16b8a403c558dc40f0f026a779c4062b228c7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
